### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by jeonghyoon** [bbahna/typescript-react#16]
- [x] 1. [Create] 저장 후, input이 빈칸이 되도록 수정
- [x] 2. [Create] user/date data.json 추가
- [x] 3. [Read] 내용이 길어지면 안보이는 ui 개선
- [x] 4. [Update] 저장 button '수정했습니다'로 알림문구 수정
- [x] 5. [Update] 배경색도 edit 가능하도록 수정
- [x] 6. [Update] 취소 button 추가

**Comment by bbahna** [comment]
계정설정을 잘못해서 새 브랜치에서 다시 커밋,푸시

**Comment by jeonghyoon** [comment]
-> git config 설정이 잘못되어서 새 브랜치에서 다시 커밋,푸시

**Comment by jeonghyoon** [comment]
2번과 3번은 UI 수정이 필요한 부분.
고민 후 필요 시, 다시 이슈 OPEN 예정 :hammer:

**Comment by jeonghyoon** [comment]
2번과 3번 UI 변경 후 완료처리 👌
